### ISSUE TITLE
Images do not appear in Laby.net

### ISSUE THREAD

**Issue by Blotcraft** [LabyMod/server-media#222]
Hello, I get a red check when I open the blotcraft(#215) code. And it shows me the following error:
Also mention that on the page of https://laby.net/server/blotcraft the image of the server does not appear correctly as that of the country apart from that the logo does not appear in discord.

```yaml
Run joelwmale/webhook-action@master
Sending webhook request to ***
Error: Received status code: 504
Error: Received status code: undefined
(node:1512) UnhandledPromiseRejectionWarning: Error: Request failed with status code: undefined
    at error (/home/runner/work/_actions/joelwmale/webhook-action/master/dist/main.js:92:11)
    at /home/runner/work/_actions/joelwmale/webhook-action/master/dist/main.js:83:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by Blotcraft** [comment]
Thank you very much for the prompt response, How can I make my server show its logo when a user plays on it, I mean on Discord.

**Comment by JakobBruening** [comment]
We have to upload your icon at discord manually. I've done it for you :)

**Comment by Blotcraft** [comment]
thanks u very much :))
